# Default values for xrootd-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

xrootd_server:
  replicaCount: 3

image:
  repository: ghcr.io/guyzsarun/xrootd-kubernetes
  pullPolicy: IfNotPresent
  tag: "5.5.3-1.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  xrootd_port: 1094
  cmsd_port: 1213

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi