name: docker-build

on:
  push:

jobs:
  docker:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker
          push: false
          tags: latest

      - name: Push image
        run: docker push ghcr.io/guyzsarun/xrootd-kubernetes:latest