name: docker-build

on:
  workflow_dispatch:
  push:

jobs:
  docker-build:
    strategy:
      matrix:
        xrootd_version: [ 5.3.4-1,5.4.3-1,5.5.3-1.2,5.5.4-1.1 ]
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: ghcr.io/guyzsarun/xrootd-kubernetes:${{ matrix.xrootd_version }}
          build-args: |
            XROOTD_VERSION=${{ matrix.xrootd_version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: docker push ghcr.io/guyzsarun/xrootd-kubernetes:${{ matrix.xrootd_version }}
